Generated from base-vm

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -30,18 +30,20 @@ jobs:
       fail-fast: false
       matrix:
         release: [ "6.4.0","6.4.1","6.4.2", ""]
-        arch: [ "aarch64", ""]
+        arch: [ "aarch64", "", "riscv64"]
         runs: [ "ubuntu-24.04", "ubuntu-24.04-arm"]
         exclude:
           - runs: "ubuntu-24.04-arm"
             arch: ""
+          - runs: "ubuntu-24.04-arm"
+            arch: "riscv64"
 
     runs-on: ${{ matrix.runs }}
     name: sshfs DragonflyBSD
     env:
       MYTOKEN : ${{ secrets.MYTOKEN }}
       MYTOKEN2: "value2"
-      SEC_VBOX : ${{ secrets.SEC_VBOX }}
+      SEC_VBOX : ${{ vars.SEC_VBOX }}
       DEBUG: 1
     steps:
     - uses: actions/checkout@v4
@@ -64,9 +66,14 @@ jobs:
           echo "arch is empty"
           echo "run=true" >> $GITHUB_OUTPUT
         elif [ -e "conf/${_release}-${_arch}.conf" ]; then
-          #ok, go ahead
           echo "conf exists: conf/${_release}-${_arch}.conf"
-          echo "run=true" >> $GITHUB_OUTPUT
+          #ok, go ahead
+          if [[ "$(echo "DragonflyBSD" | tr '[:upper:]' '[:lower:]')-${_arch}" == "freebsd-riscv64" ]]; then
+            echo "The DragonflyBSD-${_arch} doesn't support sshfs, skip."
+            echo "run=false" >> $GITHUB_OUTPUT
+          else
+            echo "run=true" >> $GITHUB_OUTPUT
+          fi
         else
           echo "The release ${_release} doesn't support ${_arch}, skip."
           echo "run=false" >> $GITHUB_OUTPUT
@@ -153,18 +160,20 @@ jobs:
       fail-fast: false
       matrix:
         release: [ "6.4.0","6.4.1","6.4.2", ""]
-        arch: [ "aarch64", ""]
+        arch: [ "aarch64", "", "riscv64"]
         runs: [ "ubuntu-24.04", "ubuntu-24.04-arm"]
         exclude:
           - runs: "ubuntu-24.04-arm"
             arch: ""
+          - runs: "ubuntu-24.04-arm"
+            arch: "riscv64"
 
     runs-on: ${{ matrix.runs }}
     name: nfs DragonflyBSD
     env:
       MYTOKEN : ${{ secrets.MYTOKEN }}
       MYTOKEN2: "value2"
-      SEC_VBOX : ${{ secrets.SEC_VBOX }}
+      SEC_VBOX : ${{ vars.SEC_VBOX }}
       DEBUG: 1
     steps:
     - uses: actions/checkout@v4
@@ -189,7 +198,12 @@ jobs:
         elif [ -e "conf/${_release}-${_arch}.conf" ]; then
           #ok, go ahead
           echo "conf exists: conf/${_release}-${_arch}.conf"
-          echo "run=true" >> $GITHUB_OUTPUT
+          if [[ "$(echo "DragonflyBSD" | tr '[:upper:]' '[:lower:]')-${_arch}" == "freebsd-riscv64" ]]; then
+            echo "The DragonflyBSD-${_arch} doesn't support nfs, skip."
+            echo "run=false" >> $GITHUB_OUTPUT
+          else
+            echo "run=true" >> $GITHUB_OUTPUT
+          fi
         else
           echo "The release ${_release} doesn't support ${_arch}, skip."
           echo "run=false" >> $GITHUB_OUTPUT
@@ -269,25 +283,26 @@ jobs:
 
 
 
-
-
-  test:
+  testscp:
     strategy:
       fail-fast: false
       matrix:
         release: [ "6.4.0","6.4.1","6.4.2", ""]
-        arch: [ "aarch64", ""]
+        arch: [ "aarch64", "", "riscv64"]
         runs: [ "ubuntu-24.04", "ubuntu-24.04-arm"]
         exclude:
           - runs: "ubuntu-24.04-arm"
             arch: ""
+          - runs: "ubuntu-24.04-arm"
+            arch: "riscv64"
 
     runs-on: ${{ matrix.runs }}
-    name: DragonflyBSD
+    name: scp DragonflyBSD
     env:
       MYTOKEN : ${{ secrets.MYTOKEN }}
       MYTOKEN2: "value2"
-      SEC_VBOX : ${{ secrets.SEC_VBOX }}
+      SEC_VBOX : ${{ vars.SEC_VBOX }}
+      DEBUG: 1
     steps:
     - uses: actions/checkout@v4
     - name: Check arch
@@ -312,6 +327,135 @@ jobs:
           #ok, go ahead
           echo "conf exists: conf/${_release}-${_arch}.conf"
           echo "run=true" >> $GITHUB_OUTPUT
+        else
+          echo "The release ${_release} doesn't support ${_arch}, skip."
+          echo "run=false" >> $GITHUB_OUTPUT
+        fi
+    - name: Creating Web console
+      if: ${{ steps.check.outputs.run == 'true' }}
+      uses: vmactions/cf-tunnel@v0
+      id: tunnel
+      with:
+        protocol: http
+        port: 8000
+    - name: Test in DragonflyBSD
+      if: ${{ steps.check.outputs.run == 'true' }}
+      id: test
+      uses: vmactions/dragonflybsd-vm@237ef5a05c81900568c1af9488faf8c23d67b0ce
+      with:
+        envs: 'DEBUG MYTOKEN MYTOKEN2'
+        prepare: |
+          pkg install -y socat
+        release: ${{ matrix.release }}
+        arch: ${{ matrix.arch }}
+        nat: |
+          "10022": "22"
+          "8080": "80"
+          "8443": "443"
+          udp:"8081": "80"
+        usesh: true
+        sync: scp
+        run: |
+          ls -lah /root/work
+          #don't use tree here, freebsd riscv64 doesn't have a tree
+          #tree $HOME/work/
+          if [ -z "$(ls -A $HOME/work)" ]; then
+            echo "nfs error."
+            exit 1
+          fi
+          env
+          echo "TEST_ENV=abc" >>${GITHUB_ENV}
+          if [ -n "test" ]; then
+            echo "false"
+          fi
+          if [ "test" ]; then
+            echo "test"
+          fi
+          pwd
+          ls -lah
+          whoami
+          env
+          uname -a
+          echo "OK"
+
+    - name: Test NAT
+      if: ${{ steps.check.outputs.run == 'true' }}
+      run:
+        echo "TEST_ENV=$TEST_ENV"
+        [ "$TEST_ENV" = "abc" ]
+        ssh -vvv -p 10022 -i $HOME/.ssh/host.id_rsa root@localhost "uname -a;whoami;pwd"
+    - name: Test custom shell
+      if: ${{ steps.check.outputs.run == 'true' }}
+      shell: dragonflybsd {0}
+      run: |
+        pwd
+        cd $GITHUB_WORKSPACE;
+        pwd
+          if [ -n "test" ]; then
+            echo "false"
+          fi
+          if [ "test" ]; then
+            echo "test"
+          fi
+          pwd
+          ls -lah
+          whoami
+          env
+          uname -a
+          echo "OK"
+
+
+
+
+
+  test:
+    strategy:
+      fail-fast: false
+      matrix:
+        release: [ "6.4.0","6.4.1","6.4.2", ""]
+        arch: [ "aarch64", "", "riscv64"]
+        runs: [ "ubuntu-24.04", "ubuntu-24.04-arm"]
+        exclude:
+          - runs: "ubuntu-24.04-arm"
+            arch: ""
+          - runs: "ubuntu-24.04-arm"
+            arch: "riscv64"
+
+    runs-on: ${{ matrix.runs }}
+    name: DragonflyBSD
+    env:
+      MYTOKEN : ${{ secrets.MYTOKEN }}
+      MYTOKEN2: "value2"
+      SEC_VBOX : ${{ vars.SEC_VBOX }}
+    steps:
+    - uses: actions/checkout@v4
+    - name: Check arch
+      id: check
+      run: |
+        _release="${{ matrix.release }}"
+        if [ -z "$_release" ]; then
+          . conf/default.release.conf
+          _release="$DEFAULT_RELEASE"
+        fi
+
+        _arch="${{ matrix.arch }}"
+        if [ "${_arch}" = "x86_64" ]; then
+          _arch=""
+        fi
+
+        if [ -z "${_arch}" ]; then
+          #ok, go ahead
+          echo "arch is empty"
+          echo "run=true" >> $GITHUB_OUTPUT
+        elif [ -e "conf/${_release}-${_arch}.conf" ]; then
+          #ok, go ahead
+          echo "conf exists: conf/${_release}-${_arch}.conf"
+          if [[ "$(echo "DragonflyBSD" | tr '[:upper:]' '[:lower:]')-${_arch}" == "freebsd-riscv64" ]]; then
+            echo "The DragonflyBSD-${_arch} doesn't support rsync, skip."
+            echo "run=false" >> $GITHUB_OUTPUT
+          else
+            echo "run=true" >> $GITHUB_OUTPUT
+          fi
         else
           echo "The release ${_release} doesn't support ${_arch}, skip."
           echo "run=false" >> $GITHUB_OUTPUT
